### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by myfirstevercode** [Readdeo/PGOnotify#1]
If its okay if you provide a dummy-101 tutorial for this

i mean i installed everything but im having some errors which i don't know how to trace or to fix it

thank you..

http://prntscr.com/bzirxk

http://prntscr.com/bzis3c

i have installed both python 2.7+ and 3.5+ something

**Comment by SapitoSucio** [comment]
You need to install mahotas-1.4.1-cp27-none-win32.whl  from here : http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

Place it in your PGOnotify, open a CMD and run pip install -r mahotas-1.4.1-cp27-none-win32.whl

**Comment by gatomiaurex** [comment]
Having the same problem as him, the solution you provided doesn't work, it gives me this error

> Exception: Traceback (most recent call last): File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main status = self.run(options, args) File "c:\python27\lib\site-packages\pip\commands\install.py", line 287, in run wheel_cache File "c:\python27\lib\site-packages\pip\basecommand.py", line 295, in populate_requirement_set wheel_cache=wheel_cache): File "c:\python27\lib\site-packages\pip\req\req_file.py", line 84, in parse_requirements filename, comes_from=comes_from, session=session File "c:\python27\lib\site-packages\pip\download.py", line 414, in get_file_content content = auto_decode(f.read()) File "c:\python27\lib\site-packages\pip\utils\encoding.py", line 31, in auto_decode return data.decode(locale.getpreferredencoding(False)) File "c:\python27\lib\encodings\cp1252.py", line 15, in decode return codecs.charmap_decode(input,errors,decoding_table) UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 45: character maps to <undefined> 

I am using Windows 7 x64, tried the 64 version of the file you suggested but it happens the same with both files.
